try:
    x = 1+2
    print(x)
except:
    print("unknown error ocurred")
finally:
    print("The addition was made, no errors")
